# Generated by Django 4.0.2 on 2022-02-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=40)),
                ('firstName', models.CharField(default='John', max_length=30)),
                ('lastName', models.CharField(default='Wick', max_length=30)),
            ],
        ),
    ]
