# Generated by Django 4.0.2 on 2022-02-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_tempadd'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='extenduser',
        #     name='groups',
        # ),
        # migrations.RemoveField(
        #     model_name='extenduser',
        #     name='user_permissions',
        # ),
        migrations.DeleteModel(
            name='TempAdd',
        ),
        # migrations.DeleteModel(
        #     name='ExtendUser',
        # ),
    ]
