# Generated by Django 4.0.2 on 2022-03-14 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('shortName', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExamScheme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('maxMarks', models.ImageField(upload_to='')),
                ('minMarks', models.IntegerField()),
                ('passingMarks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamSchemeHead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('shortName', models.CharField(max_length=10)),
                ('dean', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('shortName', models.CharField(max_length=10)),
                ('teachingScheme', models.CharField(max_length=10)),
                ('examScheme', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TeachingSchemeHead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TeachingScheme',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hours', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('teachingHead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.teachingschemehead')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTeaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schemeId', models.CharField(max_length=10)),
                ('teachingScheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.teachingscheme')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schemeId', models.CharField(max_length=10)),
                ('teachingScheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.examscheme')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=30)),
                ('degree', models.CharField(max_length=15)),
                ('duration', models.FloatField()),
                ('sessionalType', models.CharField(max_length=20)),
                ('maxSessions', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='examscheme',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.examschemehead'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.faculty'),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
