# Generated by Django 4.0.2 on 2022-03-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0002_rename_teachinghead_teachingscheme_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examscheme',
            name='maxMarks',
            field=models.IntegerField(),
        ),
    ]
