# Generated by Django 4.0.2 on 2022-03-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0003_alter_examscheme_maxmarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectexam',
            old_name='teachingScheme',
            new_name='examScheme',
        ),
        migrations.AlterField(
            model_name='subjectexam',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subjectteaching',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
