# Generated by Django 4.0.2 on 2022-02-15 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0003_department_delete_feestructurecategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=30)),
                ('degree', models.CharField(max_length=15)),
                ('duration', models.FloatField()),
                ('sessionalType', models.CharField(max_length=20)),
                ('maxSessions', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.faculty')),
            ],
        ),
    ]
