# Generated by Django 4.0.2 on 2022-02-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0005_examschemehead'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingSchemeHead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lectures', models.IntegerField()),
                ('tutorials', models.IntegerField()),
                ('labs', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='examschemehead',
            old_name='theory',
            new_name='teamwork',
        ),
    ]
