# Generated by Django 4.0.2 on 2022-02-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0007_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examschemehead',
            name='external',
        ),
        migrations.RemoveField(
            model_name='examschemehead',
            name='maxMarks',
        ),
        migrations.RemoveField(
            model_name='examschemehead',
            name='minMarks',
        ),
        migrations.RemoveField(
            model_name='examschemehead',
            name='practical',
        ),
        migrations.RemoveField(
            model_name='examschemehead',
            name='sessional',
        ),
        migrations.RemoveField(
            model_name='examschemehead',
            name='teamwork',
        ),
        migrations.RemoveField(
            model_name='teachingschemehead',
            name='labs',
        ),
        migrations.RemoveField(
            model_name='teachingschemehead',
            name='lectures',
        ),
        migrations.RemoveField(
            model_name='teachingschemehead',
            name='tutorials',
        ),
        migrations.AddField(
            model_name='examschemehead',
            name='type',
            field=models.CharField(default=0, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teachingschemehead',
            name='type',
            field=models.CharField(default=0, max_length=20, null=True),
        ),
    ]
