# Generated by Django 4.0.2 on 2022-02-24 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0008_remove_examschemehead_external_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='examScheme',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teachingScheme',
        ),
        migrations.DeleteModel(
            name='ExamSchemeHead',
        ),
        migrations.DeleteModel(
            name='TeachingSchemeHead',
        ),
    ]
