# Generated by Django 4.0.2 on 2022-02-24 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0009_remove_subject_examscheme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchemeHead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TeachingSchemeHead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='examScheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrar.examschemehead'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teachingScheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrar.teachingschemehead'),
        ),
    ]
