# Generated by Django 4.0.2 on 2022-02-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
