# Generated by Django 4.0.2 on 2022-02-07 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_extenduser_userid_alter_extenduser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primaryContact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('photo', models.ImageField(upload_to='images')),
                ('secondaryContact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('currentAdd', models.CharField(max_length=40)),
                ('currentCity', models.CharField(max_length=20)),
                ('currentState', models.CharField(max_length=20)),
                ('permAdd', models.CharField(max_length=40)),
                ('permCity', models.CharField(max_length=20)),
                ('permState', models.CharField(max_length=20)),
                ('altEmail', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('bloodGroup', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
