# Generated by Django 4.0.2 on 2022-02-09 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_feestructurecatagory_feestructurehead'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeeStructureCatagory',
            new_name='FeeStructureCategory',
        ),
    ]
