# Generated by Django 4.0.2 on 2022-02-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_extenduser_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeeStructureCategory',
        ),
        migrations.DeleteModel(
            name='FeeStructureHead',
        ),
    ]
